/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskInput: typeof import('./src/components/TaskInput.vue')['default']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
    TodoApp: typeof import('./src/components/TodoApp.vue')['default']
  }
}
